### ISSUE TITLE
Respawn Skull Not Showing

### ISSUE THREAD

**Issue by AisuDracov** [GeneralPantsuIsBadAtCoding/Azure-Peak#863]
Issue reported from  Round ID: 742 (AZURE PEAK)

Reporting client version: 515.1646

Joined the round as voyager to see what all was going on as I debated what/who I wanted to play as. However, the skull icon to respawn/orbit folks didn't show. Closed the game and reopened, still didn't show. Even restarted byond, just in case and still no luck. I even tried clicking on the area it would be, just in case the icon was invisible but the button still functioned, but alas, here I am, reporting this bug.

**Comment by Lutowski** [comment]
Bug occurred on a TM. Will re-add respawn verb so this doesn't repeat.
